return {
  foreground = "#ffffff",
  background = "#16181a",
  cursor_bg = "#ffffff",
  cursor_border = "#ffffff",
  cursor_fg = "#16181a",
  selection_bg = "#3c4048",
  selection_fg = "#ffffff",
  ansi = {
    "#16181a",
    "#ff6e5e",
    "#9ece6a",
    "#f1ff5e",
    "#5ea1ff",
    "#bd5eff",
    "#5ef1ff",
    "#ffffff",
  },
  brights = {
    "#3c4048",
    "#ff6e5e",
    "#5eff6c",
    "#f1ff5e",
    "#5ea1ff",
    "#bd5eff",
    "#5ef1ff",
    "#ffffff",
  },
  tab_bar = {
    -- background = "#15161e",
    background = "#16181a",
    new_tab = {
      bg_color = '#16181a',
      fg_color = '#ffffff',
    },
    active_tab = {
      bg_color = "#3c4048",
      fg_color = '#ffffff',
    },
    inactive_tab = {
      bg_color = '#16181a',
      fg_color = '#707070',
    },
  },
}
