# Profiling
#
# uncomment to profile startup time using:
# time  zsh -i -c exit > statuptime.txt
#
# (see also last line)
# zmodload zsh/zprof

# set path
path=($HOME/Library/Haskell/bin $path)
path=($HOME/bin/SuperCollider $path)
path=(/usr/local/opt/ruby/bin $path)
path=($HOME/.cabal/bin $path)
path=($HOME/.local/bin $path)
path=($HOME/bin $path)
path=($HOME/bin/bin $path)
path=($HOME/.dotfiles/bin $path)
path=("/usr/local/sbin" $path)
path=("/usr/local/bin" $path)
path=(/home/linuxbrew/.linuxbrew/bin $path)

# typeset -U path

source ~/.dotfiles/zsh/sourceables.sh
source ~/.dotfiles/zsh/aliases.sh
source ~/.dotfiles/zsh/completion.zsh

# history
export HISTSIZE=5000
export SAVEHIST=5000
export HISTFILE=~/.zsh_history
setopt share_history # share command history data
setopt hist_ignore_dups

# edit commands in vim
autoload -z edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# exports
export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
export GOPATH=$HOME/.go
# use this to get sysroot path
# $(rustc --print sysroot)
# ..but use hard coded value to increase shell startup time
export RUST_SRC_PATH="$HOME/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src"

# set the default system editor
export VISUAL=nvim
export EDITOR="$VISUAL"
export GIT_EDITOR="$VISUAL"
export MANPAGER="nvim -u ~/.vim/vimrc0 -c 'set ft=man' -"
export LC_ALL=en_US.UTF-8

# browse z's most recent directories using fzf
function r() {
  local dir=$(z | sort -rn | fzf | awk '{ print $2 }')
  if [[ "$dir" != '' ]]; then
    cd "$dir"
  fi
}

# browse bookmarks
function c() {
    local dest_dir=$(bookmarks_glob_echo | fzf)
    if [[ $dest_dir != '' ]]; then
        cd "$dest_dir"
    fi
}

# add bookmark
function bkm() {
    pwd >> ~/.shell_bookmarks
    echo "Added bookmark:" $(pwd)
}

function openNautilus() {
  if [[ $1 != '' ]]; then
    nautilus $1 --no-desktop 2> /dev/null
  else
    nautilus --no-desktop 2> /dev/null
  fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# uncomment to profile startup time
# zprof
