# Profiling
#
# uncomment to profile startup time using:
# time  zsh -i -c exit > statuptime.txt
#
# (see also last line)
# zmodload zsh/zprof

# allow bash-style comments
setopt interactivecomments

# set path
path=($HOME/bin $path)
path=($HOME/.dotfiles/bin $path)
path=($HOME/Library/Python/3.8/bin $path)
path=($HOME/.gem/ruby/2.6.0/bin $path)
path=($HOME/.cargo/bin $path)

# typeset -U path

source ~/.dotfiles/zsh/sourceables.sh
source ~/.dotfiles/zsh/aliases.sh
source ~/.dotfiles/zsh/completion.zsh

# history
export HISTSIZE=5000
export SAVEHIST=5000
export HISTFILE=~/.zsh_history
setopt share_history # share command history data
setopt hist_ignore_dups

# edit commands in vim
autoload -z edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# exports
export VISUAL=nvim
export EDITOR="$VISUAL"
export GIT_EDITOR="$VISUAL"
export MANPAGER='nvim +Man!'
export LC_ALL=en_US.UTF-8

# browse z's most recent directories using fzf
function r()
{
  local dir=$(z | sort -rn | fzf | sed 's/^[^\/]*//g')
  if [[ "$dir" != '' ]]; then
    cd "$dir"
  fi
}

# browse bookmarks
function c()
{
  local bookmarks="$HOME/.shell_bookmarks"
  if [[ -f "$bookmarks" ]] then
    local dest_dir=$(cat "$bookmarks" | fzf)
    if [[ "$dest_dir" != '' ]]; then
      cd "$dest_dir"
    fi
  else
    echo "No bookmarks. To add the current directory use: bkm"
  fi
}

# add bookmark
function bkm()
{
  pwd >> ~/.shell_bookmarks
  echo "Added bookmark:" $(pwd)
}

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS='--color=bw'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# eval "$(rbenv init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# uncomment to profile startup time
# zprof
