export URBIT_HOME=$HOME/src/urbit/urb
export MUSIC_SUITE_DIR=$HOME/src/music-suite

source ~/.bash_aliases
source ~/.bashrc

# enable auto-completion for git
if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
    . /usr/local/etc/bash_completion.d/git-completion.bash
fi
if [ -f /usr/local/etc/bash_completion.d/git-prompt.sh ]; then
    . /usr/local/etc/bash_completion.d/git-prompt.sh
fi
# tmux auto-completion
if [ -f /usr/local/etc/bash_completion.d/tmux ]; then
    . /usr/local/etc/bash_completion.d/tmux
fi

export PATH="$HOME/.cargo/bin:$PATH"
